copy Heatmaps.ipynb aguascalientes
copy Heatmaps.ipynb baja_california
copy Heatmaps.ipynb baja_california_sur
copy Heatmaps.ipynb campeche
copy Heatmaps.ipynb chiapas
copy Heatmaps.ipynb chihuahua
copy Heatmaps.ipynb coahuila
copy Heatmaps.ipynb colima
copy Heatmaps.ipynb distrito_federal
copy Heatmaps.ipynb durango
copy Heatmaps.ipynb estado_de_mexico
copy Heatmaps.ipynb guanajuato
copy Heatmaps.ipynb guerrero
copy Heatmaps.ipynb hidalgo
copy Heatmaps.ipynb jalisco
copy Heatmaps.ipynb michoacan
copy Heatmaps.ipynb morelos
copy Heatmaps.ipynb nayarit
copy Heatmaps.ipynb nuevo_leon
copy Heatmaps.ipynb oaxaca
copy Heatmaps.ipynb puebla
copy Heatmaps.ipynb queretaro
copy Heatmaps.ipynb quintana_roo
copy Heatmaps.ipynb san_luis_potosi
copy Heatmaps.ipynb sinaloa
copy Heatmaps.ipynb sonora
copy Heatmaps.ipynb tabasco
copy Heatmaps.ipynb tamaulipas
copy Heatmaps.ipynb tlaxcala
copy Heatmaps.ipynb veracruz
copy Heatmaps.ipynb yucatan
copy Heatmaps.ipynb zacatecas